---
title: "Ukraine-Russia"
author: "Maximilian Agostini, Tasja Mueller, Ben Guetzkow, Pontus Leander, Jannis Kreienkamp"
date: "3/3/2022"
output:
  html_document:
    code_folding: hide
    mathjax: default
    theme: united
    toc: yes
    toc_float: yes
    number_sections: TRUE
  pdf_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
cat("\014") # clear console
rm(list=ls()) # clear workspace
gc # garbage collector

require(pacman)
p_load(metafor, tidyr, dplyr, tinytex, knitr, kableExtra, DescTools, reshape2, metaSEM, lavaan, semPlot, psych, ggplot2, MplusAutomation, bmlm)

set.seed(52) # set overall random seed for reproducibility
```

# Load Data
```{r LoadRawBase, echo=T, warning=F, message=F}
# Import Data
dtRaw <- haven::read_spss("M:/.00 Research/Datasets/Ukraine+Russia_March+5,+2022_17.sav")
```

# Prepare Data
## Cleaning (not collected)
```{r}
tmp <- dtRaw

# exclude practice trials (before we launched on MTurk which was at 2022-02-25 01:42:04)
tmp$StartDate <- as.POSIXct(tmp$StartDate)
tmp <- tmp[tmp$StartDate > as.POSIXct("2022-02-25 01:40:00", tz = "UTC"),]

# exclude participants that did not get to the informed consent (ethics)
tmp <- tmp[tmp$Progress > 95,]

df <- tmp; rm(tmp, dtRaw)
```
We collected a total of `nrow(tmp)` participants.

## Cleaning (data quality)
```{r}
# identify duplicate IPs (but only the second entry! we keep the first one)
dupli <- df[duplicated(df$IPAddress),]
paste("We removed", nrow(dupli), "entries for entering the study from the same IP (difficult to establish independence of measurements).", sep = " ")
df <- df[!duplicated(df$IPAddress),]; rm(dupli)

# check for straightliner
# isolate respondents who have straightlined outside a the median categories (b/c all "neither agree nor disagree" might be meaningful response) 
strLine <- df %>%
  dplyr::select(ResponseId, SDO_01, SDO_02, SDO_03, SDO_04) %>%
  na.omit() %>% # remove people who have missing data on one of the three items
  mutate(mean = rowMeans(dplyr::select(., contains("SDO"))), 
         sd = matrixStats::rowSds(as.matrix(dplyr::select(., contains("SDO"))))) %>% # calculate row-means and row-sds 
  filter(sd == 0, mean != 5, mean != 6)
paste("We removed", nrow(strLine), "entries for straighlining on the SDO scale.", sep = " ")

# remove straightliners
  df <- df %>%
    filter(!ResponseId %in% strLine$ResponseId); rm(strLine)

```


## Share Data
```{r}
share <- df %>%
  select(-contains("mTurk"),
         -starts_with("t_"),
         -contains("_DO_"),
         -contains("TEXT"),
         -contains("Date"),
         -contains("Name"),
         -contains("Email"),
         -contains("Location"),
         -contains("User"),
         -contains("_Other"),
         -ExternalReference,
         -ResponseId,
         -Duration__in_seconds_,
         -DistributionChannel,
         -Finished,
         -debrief,
         -Status,
         -IPAddress,
         -Progress,
         -end_positive_how)

haven::write_sav(share, "M:/.00 Research/Datasets/cleaned/2022_03_05_Ukraine-Russia.sav"); rm(share)

```

## Prepare scales
```{r}



```


